name: Deploy to CloudBase Static Hosting

on:
    push:
        branches:
            - main # 主分支推送时触发
    pull_request:
        branches:
            - main # PR时触发（可选）

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  cache: 'npm' # 启用npm缓存加速构建

            - name: Install dependencies
              run: npm ci # 使用npm ci替代npm install，更适合CI环境

            - name: Build project
              run: npm run build

            - name: Install CloudBase CLI
              run: npm install -g @cloudbase/cli

            - name: Login CloudBase CLI
              run: tcb login --apiKeyId ${{ secrets.TCB_SECRET_ID }} --apiKey ${{ secrets.TCB_SECRET_KEY }}

            - name: Deploy to CloudBase Static Hosting
              run: |
                  tcb hosting deploy ./dist /home -e ${{ secrets.TCB_ENV_ID }}
